# User Routes HTTP REQUESTS

###* getAll
GET http://localhost:3000/api/agendalo/user/getAll

###* getOne
GET http://localhost:3000/api/agendalo/user/getOne

###* createUser
POST http://localhost:3000/api/agendalo/user/create
Content-Type: application/json
{ 
    "name": "Juan",
    "lastName": "López",
    "email": "octavio@gmail.com",
    "title": "Sr",
    "gender": "Masculino",
    "birthDate": "26-11-2023",
    "password": "12345678"
}